# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do | config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "respond_repository"

  config.vm.network "private_network", ip: "192.168.87.10"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "deploy.yml"
    ansible.limit = "all,localhost" # Prevent ansible from ignoring localhost tasks
  end
end
